# Generated by Django 3.0.2 on 2020-01-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.PositiveSmallIntegerField()),
                ('course', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=1)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('date_of_admission', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
            ],
        ),
    ]
