# Generated by Django 3.0.2 on 2020-01-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0004_auto_20200110_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:GLT1Kqob5UDEML61gCyjnAcfMXgkdP3wGcg45XqPo7XvvviCSQAuru5C&s', max_length=500),
        ),
    ]
