# Generated by Django 3.0.2 on 2020-01-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0005_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.URLField(default='https://pwcenter.org/sites/default/files/default_images/default_profile.png', max_length=500),
        ),
    ]
