# Generated by Django 3.0.2 on 2020-01-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0006_auto_20200110_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode',
            field=models.URLField(default='http://barcodes4.me/barcode/c128a/<django.db.models.fields.PositiveSmallIntegerField>.png?margin=5&height=60&resolution=2', editable=False, max_length=500),
        ),
    ]
