# Generated by Django 2.1 on 2020-01-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0008_remove_student_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')], default=1),
        ),
    ]
