# Generated by Django 2.1 on 2020-01-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0009_auto_20200112_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('B.A.', (('BAHENG', 'B.A (Hons) English'), ('BAPENG', 'B.A. (Programme) compulsory English course'), ('BAHHIN', 'B.A (Hons) Hindi'), ('BAPHIN', 'B.A. (Programme) compulsory Hindi course'), ('BAHHIS', 'B.A. (Hons) History'), ('BAPHIS', 'B.A. (Programme)with History'), ('BAHPOL', 'B.A (Hons) Political Science'), ('BAPPOL', 'B.A (Prog.) with Political Science'), ('BAPECO', 'B.A. (Programme) with Economics'), ('BAPAC', 'B.A. Program Discipline and Application Course'))), ('B.Com', (('BCPENG', 'B.Com (Programme) compulsory English course'), ('BCPHIN', 'B.Com (Programme ) compulsory Hindi course'), ('BCH', 'B.Com (Hons)'), ('BCP', 'B.Com (Prog.)'))), ('B.Sc.', (('BSHCS', 'B.Sc. (Hons) Computer Science'), ('BSHGEO', 'B.Sc. (Hons) Geology'), ('BSHMIC', 'B.Sc (Hons) Microbiology'), ('BSHSTA', 'B.Sc. (Hon.) Statistics'), ('BSHMAT', 'B.Sc(Hons) Mathematics'))), ('BMS', 'Bachelor of Management Studies'), ('BJMC', 'BJMC')], default=1, max_length=50),
        ),
    ]
