# Generated by Django 2.1 on 2020-01-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0010_auto_20200112_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(choices=[('A', (('A+', 'A +ve'), ('A-', 'A -ve'))), ('B', (('B+', 'B +ve'), ('B-', 'B -ve'))), ('AB', (('AB+', 'AB +ve'), ('AB-', 'AB -ve'))), ('O', (('O+', 'O +ve'), ('O-', 'O -ve')))], default=1, max_length=3),
        ),
    ]
